# This is an action definition file, which has three parts: the goal
# the result, and the feedback.
# Part 1: the goal.
#
# The coordinates x and y, where the robot should delivery the coffe
float64 x
float64 y

---

# Part 2: the result, sent by action server unpon completion
#
# The number of the robot who executed this action and the status of the requested delivery.
int32 robot
int32 status 

---

# Part 3: the feedback, to be sent periodically by server
#
# We don't have any feedback for this action